matrix:
  include:
    - language: go
      go:
        - 1.10.x
      before_install:
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
      script:
        - ./go.test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
        - cd client
        - npm install
        - npm run test:ci
        - npm run build
